#!/usr/bin/env python3
"""Generate 16x16 palette-indexed sprite .bin files for Pac-Man and ghosts.

Each output file is a raw 256-byte blob (16 rows of 16 bytes, row-major).
Byte values are palette indices, interpreted by SPRITES.X68:SPRITE_DRAW:

    0 = transparent (not drawn)
    1 = primary    (Pac-Man body color  / ghost body color)
    2 = secondary  (eye white)
    3 = tertiary   (pupil)

Run once from the repo root: `python3 tools/build_sprites.py`.
The .bin outputs land in DATA/SPRITES/ and are consumed via INCBIN.
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "DATA" / "SPRITES"

W = H = 16
GLYPHS = {".": 0, "Y": 1, "B": 1, "W": 2, "P": 3}


def parse(art):
    rows = [r for r in art.strip("\n").splitlines() if r != ""]
    assert len(rows) == H, f"expected {H} rows, got {len(rows)}"
    out = bytearray()
    for r in rows:
        assert len(r) == W, f"row {r!r} length {len(r)} != {W}"
        for ch in r:
            out.append(GLYPHS[ch])
    return bytes(out)


def rotate_cw(data):
    out = bytearray(W * H)
    for r in range(H):
        for c in range(W):
            out[c * W + (H - 1 - r)] = data[r * W + c]
    return bytes(out)


def rotate_180(data):
    return rotate_cw(rotate_cw(data))


def rotate_ccw(data):
    return rotate_cw(rotate_cw(rotate_cw(data)))


def write_sprite(name, data):
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUT_DIR / f"{name}.bin"
    path.write_bytes(data)
    assert len(data) == 256, f"{name}: {len(data)} bytes, expected 256"
    print(f"  {path.relative_to(ROOT)} ({len(data)} B)")


# --- Pac-Man, right-facing ---------------------------------------------------
# Frame 0: slight wedge mouth open to the right.
PAC_R0 = """\
....YYYYYYYY....
..YYYYYYYYYYYY..
.YYYYYYYYYYYYY..
.YYYYYYYYYYY....
YYYYYYYYYYY.....
YYYYYYYYYY......
YYYYYYYYY.......
YYYYYYYYY.......
YYYYYYYYY.......
YYYYYYYYY.......
YYYYYYYYYY......
YYYYYYYYYYY.....
.YYYYYYYYYYY....
.YYYYYYYYYYYYY..
..YYYYYYYYYYYY..
....YYYYYYYY....
"""

# Frame 1: wide-open wedge to the right.
PAC_R1 = """\
....YYYYYYYY....
..YYYYYYYYYYYY..
.YYYYYYYYYY.....
.YYYYYYYY.......
YYYYYYYY........
YYYYYYY.........
YYYYY...........
YYY.............
YYY.............
YYYYY...........
YYYYYYY.........
YYYYYYYY........
.YYYYYYYY.......
.YYYYYYYYYY.....
..YYYYYYYYYYYY..
....YYYYYYYY....
"""

# --- Ghost body, two frames -------------------------------------------------
# Solid dome and body; bottom three rows form four wave-feet.
GHOST_B0 = """\
....BBBBBBBB....
..BBBBBBBBBBBB..
.BBBBBBBBBBBBBB.
.BBBBBBBBBBBBBB.
BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB
BBB.BBB.BBB.BBBB
BB...BB.BB...BBB
B....B...B....BB
"""

GHOST_B1 = """\
....BBBBBBBB....
..BBBBBBBBBBBB..
.BBBBBBBBBBBBBB.
.BBBBBBBBBBBBBB.
BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB
BBBB.BBB.BBB.BBB
BBB.BB.BB.BB.BBB
BB.BB.BB.BB.BB.B
"""

# --- Ghost eyes, four directions -------------------------------------------
# Two eye sockets centered on rows 5-8, cols 3-5 (left) and 10-12 (right).
# Pupils (P) shift within each socket to indicate facing.
EYES_R = """\
................
................
................
................
................
...WWW....WWW...
...WPP....WPP...
...WPP....WPP...
...WWW....WWW...
................
................
................
................
................
................
................
"""

EYES_L = """\
................
................
................
................
................
...WWW....WWW...
...PPW....PPW...
...PPW....PPW...
...WWW....WWW...
................
................
................
................
................
................
................
"""

EYES_U = """\
................
................
................
................
................
...WPW....WPW...
...WPW....WPW...
...WWW....WWW...
...WWW....WWW...
................
................
................
................
................
................
................
"""

EYES_D = """\
................
................
................
................
................
...WWW....WWW...
...WWW....WWW...
...WPW....WPW...
...WPW....WPW...
................
................
................
................
................
................
................
"""


def main():
    pac_r0 = parse(PAC_R0)
    pac_r1 = parse(PAC_R1)

    write_sprite("PACMAN_R0", pac_r0)
    write_sprite("PACMAN_R1", pac_r1)
    write_sprite("PACMAN_D0", rotate_cw(pac_r0))
    write_sprite("PACMAN_D1", rotate_cw(pac_r1))
    write_sprite("PACMAN_L0", rotate_180(pac_r0))
    write_sprite("PACMAN_L1", rotate_180(pac_r1))
    write_sprite("PACMAN_U0", rotate_ccw(pac_r0))
    write_sprite("PACMAN_U1", rotate_ccw(pac_r1))

    write_sprite("GHOST_B0", parse(GHOST_B0))
    write_sprite("GHOST_B1", parse(GHOST_B1))

    write_sprite("EYES_L", parse(EYES_L))
    write_sprite("EYES_U", parse(EYES_U))
    write_sprite("EYES_R", parse(EYES_R))
    write_sprite("EYES_D", parse(EYES_D))


if __name__ == "__main__":
    main()
